name: mylib

dependencies:
- base >= 4.7 && <= 5

library:
  source-dirs: src

tests:
  mytests:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - mylib
      - hspec
      - QuickCheck